name: Deploy
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
 
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/repo/TeamTalk-5-em-docker"
 
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.SSHKEY }}
        script: |
            cd ./repo/TeamTalk-5-em-docker/
            docker stop ttda
            docker rm ttda
            docker build -t ttd .
            docker run --name ttda --restart=on-failure -dv /root/repo/comTT:/server/data -p 10333:10333 -p 10333:10333/udp ttd